dist: trusty
sudo: false

language: node_js
node_js:
  - "12"
addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

before_script:
  - bundle exec rails runner "Webdrivers::Chromedriver.update"

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
